### ISSUE TITLE
Spam / Trash buttons not working

### ISSUE THREAD

**Issue by roundhill** [Automattic/notifications-panel#24]
If you spam or trash a comment, nothing seems to happen.

**Comment by roundhill** [comment]
```
Uncaught TypeError: Cannot read property 'id' of undefined
    at findNextNoteId (app:///./client/notifications/notifications-panel/src/templates/index.jsx:126:28)
    at advanceToNextNote (app:///./client/notifications/notifications-panel/src/state/action-middleware/ui/index.js:54:52)
    at eval (app:///./client/notifications/notifications-panel/src/state/action-middleware/index.js:44:28)
    at Array.forEach (native)
    at Object.eval [as dispatch] (app:///./client/notifications/notifications-panel/src/state/action-middleware/index.js:43:30)
    at Object.dispatch (<anonymous>:2:1507)
    at trashNote (app:///./client/notifications/notifications-panel/src/flux/note-actions.js:87:18)
    at onToggle (app:///./client/notifications/notifications-panel/src/templates/button-trash.jsx:38:51)
    at Object.ReactErrorUtils.invokeGuardedCallback (app:///./~/react-dom/lib/ReactErrorUtils.js:70:16)
    at executeDispatch (app:///./~/react-dom/lib/EventPluginUtils.js:85:21)
```
